<a href="https://colab.research.google.com/github/vaishnavanil541-cmd/data-science-L1/blob/main/dsvlab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
 num = int (input("Enter an integer"))

Enter an integer6


In [6]:
for i in range(1,11):
  print(f'{num} x {i} ={num*i}')

6 x 1 =6
6 x 2 =12
6 x 3 =18
6 x 4 =24
6 x 5 =30
6 x 6 =36
6 x 7 =42
6 x 8 =48
6 x 9 =54
6 x 10 =60


In [11]:
a = float(input("Enter first number"))
b = float(input("Enter second number"))
print(f'Addition:{a+b}')
print(f'Substraction:{a-b}')
print(f'Multiplication:{a*b}')
print(f'Division: {a/b}')
print(f'Floor Division:{a//b}')
print(f'Modulus:{a%b}')
print(f'Exponent;{a**b}')

Enter first number5
Enter second number6.5
Addition:11.5
Substraction:-1.5
Multiplication:32.5
Division: 0.7692307692307693
Floor Division:0.0
Modulus:5.0
Exponent;34938.56214843421


In [12]:
num=[12,15,18,10,20]
total=0
for x in num:
  total +=x
  print(total)
  avg =total/len(num)
  print(avg)


12
2.4
27
5.4
45
9.0
55
11.0
75
15.0


In [14]:
import numpy as np
marks = np.array([72,65,81,54,90])
print("Array:",marks)
print("type:",type(marks))

Array: [72 65 81 54 90]
type: <class 'numpy.ndarray'>


In [31]:
marks = np.array([[[72,65,81],
                 [54,90,76],
                [54,90,76]]])

print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'Shape:{marks.shape}')
print(f'Size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[[72 65 81]
  [54 90 76]
  [54 90 76]]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(1, 3, 3)
Size:9
Dimension:3


In [29]:
arr = np.array([23,12])
print(f'Array:\n{arr}')
print(f'Type:{type(arr)}')
print(f'dtype:{arr.dtype}')
print(f'Shape:{arr.shape}')
print(f'Size:{arr.size}')
print(f'Dimension:{arr.ndim}')


Array:
[23 12]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(2,)
Size:2
Dimension:1


In [33]:
marks = np.array([[[72,65,81],
                 [54,90,76],
                [54,90,76]]])

print(f'Array:\n{marks}')
print(f'Type:{type(marks)}')
print(f'dtype:{marks.dtype}')
print(f'Shape:{marks.shape}')
print(f'Size:{marks.size}')
print(f'Dimension:{marks.ndim}')

Array:
[[[72 65 81]
  [54 90 76]
  [54 90 76]]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(1, 3, 3)
Size:9
Dimension:3


In [39]:
print(f'First row:{marks[0]}')
print(f'Second row:{marks[1]}')
print(f'First column:{marks[:,0]}')
print(f'Second column:{marks[:,1]}')
print(f'Third column:{marks[:,2]}')

First row:[[72 65 81]
 [54 90 76]
 [54 90 76]]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [40]:
import numpy as np

d3array = np.array([[[72,65,81],[4,5,6]],
                    [[54,90,76],[7,8,9]],
                    [[54,90,76],[10,11,12]]])

print(f'Array:\n{d3array}')
print(f'Type:{type(d3array)}')
print(f'dtype:{d3array.dtype}')
print(f'Shape:{d3array.shape}')
print(f'Size:{d3array.size}')
print(f'Dimension:{d3array.ndim}')

Array:
[[[72 65 81]
  [ 4  5  6]]

 [[54 90 76]
  [ 7  8  9]]

 [[54 90 76]
  [10 11 12]]]
Type:<class 'numpy.ndarray'>
dtype:int64
Shape:(3, 2, 3)
Size:18
Dimension:3


In [41]:
np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
arr1 = np.array([45,67,83,56,78,90,45,36])
print(f'First four:{arr1[:4]}')
print(f'Middle:{arr1[2:6]}')
print(f'Every second value:{arr1[::2]}')
print(f'Reverse:{arr1[::-1]}')

First four:[45 67 83 56]
Middle:[83 56 78 90]
Every second value:[45 83 78 45]
Reverse:[36 45 90 78 56 83 67 45]


In [43]:
zeros = np.zeros(5)
ones = np.ones((2,3))
full = np.full((2,3),7)

print(f'Zeros:\n{zeros}')
print(f'Ones:\n{ones}')
print(f'Full:\n{full}')

Zeros:
[0. 0. 0. 0. 0.]
Ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Full:
[[7 7 7]
 [7 7 7]]


In [44]:
a=np.arange(0,10,2)
print(f'arrange:{a}')

arrange:[0 2 4 6 8]


In [46]:
print(f'arange:{b}')

arange:6.5


In [47]:
c=np.linspace(0,1,11)
print(f'arange:{c}')

arange:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [48]:
np.random.seed(42)
e=np.random.randint(1,100)
print(e)

52
